// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadMIDI() {
  return window['go']['main']['App']['LoadMIDI']();
}

export function RenderMIDI() {
  return window['go']['main']['App']['RenderMIDI']();
}

export function UnloadMIDI() {
  return window['go']['main']['App']['UnloadMIDI']();
}
